version: 2
plan:
  project-key: DEMO
  key: CONVERT
  name: Convert Helm to Marathon JSON

stages:
  - name: Build and Convert
    jobs:
      - key: BUILD
        name: Build and Convert
        tasks:
          - script:
              description: Extract and Convert Helm to Marathon JSON
              scriptBody: |
                # Ensure the script is executable
                chmod +x convert_helm_to_marathon.py
                # Run the conversion script
                python3 convert_helm_to_marathon.py

  - name: Package and Upload
    jobs:
      - key: PACKAGE
        name: Package and Upload
        tasks:
          - script:
              description: Package the Converted Files
              scriptBody: |
                if [ -f "marathon.json" ]; then
                  tar -czvf converted_chart.tgz marathon.json
                else
                  echo "marathon.json not found!"
                  exit 1
                fi

          - script:
              description: Upload to Nexus
              scriptBody: |
                if [ -f "converted_chart.tgz" ]; then
                  curl -u bamboonexus:VhaG0ng51mplengpASS \
                  -T converted_chart.tgz \
                  http://nexusdemo.climacs.net:8081/repository/bamboodemo/ \
                  -v
                else
                  echo "converted_chart.tgz not found!"
                  exit 1
                fi
