version: 2
plan:
  project-key: demo2
  key: CONVERT
  name: Convert Helm to Marathon JSON

stages:
  - name: Build and Convert
    jobs:
      - key: BUILD
        name: Build and Convert
        tasks:
          - script:
              description: Extract and Convert Helm to Marathon JSON
              environment:
                variables:
                  bamboo_build_working_directory: ${bamboo.build.working.directory}
              scriptBody: |
                # Ensure the script is executable
                chmod +x convert_helm_to_marathon.py
                # Run the conversion script
                python3 convert_helm_to_marathon.py
                # Check if marathon.json is created
                if [ -f "${bamboo_build_working_directory}/marathon.json" ]; then
                  echo "marathon.json successfully created."
                else
                  echo "marathon.json not found!"
                  exit 1
          - script:
              description: List Directory Contents After Conversion
              scriptBody: |
                echo "Listing contents of the build directory after conversion:"
                ls -l ${bamboo_build_working_directory}

  - name: Package and Upload
    jobs:
      - key: PACKAGE
        name: Package and Upload
        tasks:
          - script:
              description: List Directory Contents Before Packaging
              scriptBody: |
                echo "Listing contents of the build directory before packaging:"
                ls -l ${bamboo_build_working_directory}
          - script:
              description: Package the Converted Files
              scriptBody: |
                if [ -f "${bamboo_build_working_directory}/marathon.json" ]; then
                  tar -czvf ${bamboo_build_working_directory}/converted_chart.tgz -C ${bamboo_build_working_directory} marathon.json
                  echo "Tarball successfully created."
                else
                  echo "marathon.json not found!"
                  exit 1
          - script:
              description: Upload to Nexus
              scriptBody: |
                if [ -f "${bamboo_build_working_directory}/converted_chart.tgz" ]; then
                  curl -u bamboonexus:VhaG0ng51mplengpASS \
                  -T ${bamboo_build_working_directory}/converted_chart.tgz \
                  http://nexusdemo.climacs.net:8081/repository/bamboodemo/ \
                  -v
                  echo "Upload to Nexus successful."
                else
                  echo "converted_chart.tgz not found!"
                  exit 1
