---
- name: Install Java 11
  hosts: all
  become: yes

  tasks:
    - name: Update APT package list
      apt:
        update_cache: yes

    - name: Install Java 11
      apt:
        name: openjdk-11-jdk
        state: present
